*&---------------------------------------------------------------------*
 *& Include MZBSD1050TOP               - Module Pool   SAPMZBSD1050
 *&---------------------------------------------------------------------*
 PROGRAM SAPMZBSD1050 MESSAGE-ID ZCOMMON_MSG.

 TABLES: ZTBSD1050, ZTBSD1051, ZTBSD1040, ZSSD1050, ZSBSD50.

 DATA: OK_CODE  TYPE SY-UCOMM,
    GO_CONT  TYPE REF TO CL_GUI_CUSTOM_CONTAINER,
    GO_ALV  TYPE REF TO CL_GUI_ALV_GRID,
    GS_LAYOUT TYPE LVC_S_LAYO,
    GT_ROW  TYPE LVC_T_ROID,
    GS_ROW  TYPE LVC_S_ROID,
    GT_FCAT  TYPE LVC_T_FCAT.

 DATA: GT_BPDATA  TYPE TABLE OF ZSBSD50,
    GS_BPDATA  TYPE ZSBSD50,
    GS_ZTBSD1050 TYPE ZTBSD1050,
    GS_ZTBSD1051 TYPE ZTBSD1051,
    GT_ZTBSD1030 TYPE TABLE OF ZTBSD1030,
    GS_ZTBSD1030 LIKE LINE OF GT_ZTBSD1030.

 \* 컨펌창에 사용
 DATA: LV_ANSWER TYPE CHAR1,
    BANKCODE TYPE SY-UCOMM.
