*&---------------------------------------------------------------------*
 *& Include ZBBSD0010TOP               - Report ZBBSD0010
 *&---------------------------------------------------------------------*
 REPORT ZBBSD0010 MESSAGE-ID ZCOMMON_MSG.

 TABLES: SSCRFIELDS, ZTBSD1030.

 DATA: OK_CODE  TYPE SY-UCOMM,
    GO_DOCK  TYPE REF TO CL_GUI_DOCKING_CONTAINER,
    GO_ALV  TYPE REF TO CL_GUI_ALV_GRID,
    GS_LAYOUT TYPE LVC_S_LAYO,
    GT_ROW  TYPE LVC_T_ROID,
    GS_ROW  TYPE LVC_S_ROID,
    GT_FCAT  TYPE LVC_T_FCAT.

 DATA : GT_EXCEL   TYPE TABLE OF ALSMEX_TABLINE, " 여러 행을 가질 수 있는 데이터 구조
    GS_EXCEL   TYPE ALSMEX_TABLINE,  " 외부 데이터를 한 행씩 처리할 때 사용
    GT_ZTBSD1060 TYPE TABLE OF ZTBSD1060,
    GS_ZTBSD1060 LIKE LINE OF GT_ZTBSD1060,
    GT_ZTBSD1061 TYPE TABLE OF ZTBSD1061,
    GS_ZTBSD1061 LIKE LINE OF GT_ZTBSD1061,
    GT_DATA   TYPE TABLE OF ZSBSD60,
    GS_DATA   LIKE LINE OF GT_DATA,
    GT_ZTBSD1030 TYPE TABLE OF ZTBSD1030,
    GS_ZTBSD1030 LIKE LINE OF GT_ZTBSD1030.


 \* OLE object
 DATA: GO_EXCEL TYPE OLE2_OBJECT,
    GO_BOOKS TYPE OLE2_OBJECT,
    GO_WBOOK TYPE OLE2_OBJECT,
    GO_BOOK  TYPE OLE2_OBJECT,
    GO_SHEETS TYPE OLE2_OBJECT,
    GO_SHEET TYPE OLE2_OBJECT,
    GO_CELLS TYPE OLE2_OBJECT,
    GO_CELL  TYPE OLE2_OBJECT,
    GO_RANGE TYPE OLE2_OBJECT,
    GO_FONT  TYPE OLE2_OBJECT,
    GO_ROW  TYPE OLE2_OBJECT,
    GV_PATH  TYPE STRING,
    GV_NUM  TYPE I.


 \* 컨펌창에 사용
 DATA: LV_ANSWER TYPE CHAR1.
